AWSTemplateFormatVersion: 2010-09-09
Description: Creating internet and NAT gateway

Parameters:

  Environment:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cloudformation/vpc/environment
    Description: Select environment from parameter store

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-igw'

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: InternetGateway
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !ImportValue
        'Fn::Sub': '${Environment}-vpc'

  # EIPForNatGatewayA:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc
  #     Tags:
  #       - Key: Name
  #         Value: !Sub '${Environment}-eip-a'

  # EIPForNatGatewayB:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc
  #     Tags:
  #       - Key: Name
  #         Value: !Sub '${Environment}-eip-b'

  # NatGatewayA:
  #   Type: AWS::EC2::NatGateway
  #   DependsOn: EIPForNatGatewayA
  #   Properties:
  #     AllocationId: !GetAtt EIPForNatGatewayA.AllocationId
  #     SubnetId: !ImportValue
  #       'Fn::Sub': '${Environment}-public-a'
  #     Tags:
  #       - Key: Name
  #         Value: !Sub '${Environment}-igw-a'

  # NatGatewayB:
  #   Type: AWS::EC2::NatGateway
  #   DependsOn: EIPForNatGatewayB
  #   Properties:
  #     AllocationId: !GetAtt EIPForNatGatewayB.AllocationId
  #     SubnetId: !ImportValue
  #       'Fn::Sub': '${Environment}-public-b'
  #     Tags:
  #       - Key: Name
  #         Value: !Sub '${Environment}-igw-b'

Outputs:

  InternetGateway:
    Description: custom internet gateway
    Value: !Ref InternetGateway
    Export:
      Name: !Sub '${Environment}-igw'

  # NatGatewayA:
  #   Description: nat gateway in AZ a
  #   Value: !Ref NatGatewayA
  #   Export:
  #     Name: !Sub '${Environment}-ngw-a'

  # NatGatewayB:
  #   Description: nat gateway in AZ b
  #   Value: !Ref NatGatewayB
  #   Export:
  #     Name: !Sub '${Environment}-ngw-b'
