AWSTemplateFormatVersion: 2010-09-09
Description: Creating launch template

Parameters:

  Environment:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cloudformation/vpc/environment
    Description: Select environment from parameter store
  SshKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: select the ssh key for template

Mappings:
  RegionMap:
    us-east-1:
      "ubuntu": "ami-052efd3df9dad4825"
      "linux2ami": "ami-0cff7528ff583bf9a"
    us-east-2:
      "ubuntu": "ami-02f3416038bdb17fb"
      "linux2ami": "ami-02d1e544b84bf7502"
    us-west-1:
      "ubuntu": "ami-085284d24fe829cd0"
      "linux2ami": "ami-0d9858aa3c6322f73"
    us-west-2:
      "ubuntu": "ami-0d70546e43a941d70"
      "linux2ami": "ami-098e42ae54c764c35"
  EnvironmentMap:
    dev:
      "instancetype": "t2.nano"
    uat:
      "instancetype": "t2.micro"
    prod:
      "instancetype": "t2.micro"

Resources:
  DemoLt:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${Environment}-asg-lt'
      LaunchTemplateData:
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", linux2ami]
        InstanceType: !FindInMap [EnvironmentMap, !Ref Environment, instancetype]
        IamInstanceProfile:
          Name: !ImportValue
            'Fn::Sub': '${Environment}-asg-instance-profile'
        KeyName: !Ref SshKey
        SecurityGroupIds:
          - !ImportValue
            'Fn::Sub': '${Environment}-asg-sg'
        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            systemctl enable httpd
            systemctl start httpd
            echo "Hello World $(hostname -f)" > /var/www/html/index.html
            echo "healthy" > /var/www/html/health.html

Outputs:
  DefaultVersion:
    Description: default version of template
    Value: !GetAtt DemoLt.DefaultVersionNumber
    Export:
      Name: !Sub '${Environment}-lt-default-version'
  LatestVersion:
    Description: latest version of template
    Value: !GetAtt DemoLt.LatestVersionNumber
    Export:
      Name: !Sub '${Environment}-lt-latest-version'
  TemplateId:
    Description: template id
    Value: !Ref DemoLt
    Export:
      Name: !Sub '${Environment}-lt-id'
